package com.easy.fias.services.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "DownloadServiceSoap", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DownloadServiceSoap {


  /**
   * @return returns fias.services.DownloadFileInfo
   */
  @WebMethod(operationName = "GetLastDownloadFileInfo", action = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/GetLastDownloadFileInfo")
  @WebResult(name = "GetLastDownloadFileInfoResult", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx")
  @RequestWrapper(localName = "GetLastDownloadFileInfo", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx", className = "fias.services.GetLastDownloadFileInfo")
  @ResponseWrapper(localName = "GetLastDownloadFileInfoResponse", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx", className = "fias.services.GetLastDownloadFileInfoResponse")
  public DownloadFileInfo getLastDownloadFileInfo();

  /**
   * @return returns fias.services.ArrayOfDownloadFileInfo
   */
  @WebMethod(operationName = "GetAllDownloadFileInfo", action = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/GetAllDownloadFileInfo")
  @WebResult(name = "GetAllDownloadFileInfoResult", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx")
  @RequestWrapper(localName = "GetAllDownloadFileInfo", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx", className = "fias.services.GetAllDownloadFileInfo")
  @ResponseWrapper(localName = "GetAllDownloadFileInfoResponse", targetNamespace = "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx", className = "fias.services.GetAllDownloadFileInfoResponse")
  public ArrayOfDownloadFileInfo getAllDownloadFileInfo();

}
